name: 'Normalized Unicode'
description: 'Checks for unnormalized Unicode and optionally commits a fix if needed.'
inputs:
  transliteration:  # id of input
    description: 'The Unicode style you would like to consider standard'
    required: true
    default: 'Any-NFC'
  exit_code:
    description: 'What exit status code should it use if a file was found in need of normalization?'
    required: true
    default: 1
  commit_fix:
    description: 'If a problem is found, should the action automatically commit a fix?'
    required: true
    default: false
  token:
    description: 'A personal access token for pushing the fix to the repo. Required if you want that push to trigger workflows'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.transliteration }}
    - ${{ inputs.exit_code }}
    - ${{ inputs.commit_fix }}

