on: [push]
jobs:
  helloworld:
    runs-on: ubuntu-latest
    name: Test on self
    steps:
      - name: Get the code
        uses: actions/checkout@v2
        with:
            fetch-depth: 1
      - name: Run the Action
        id: mine
        uses: buddhist-uni/normalized-unicode-action@main
      - name: Display the result
        run: echo "Outcome=${{ steps.mine.outcome }} Conclusion=${{ steps.mine.conclusion }}"
